spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaiaDoroshenko/microservice-config.git
          default-label: main
          clone-on-start: true
          username: MaiaDoroshenko
          password: ${GIT_TOKEN}
server:
  port: 7777
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/

